### ISSUE TITLE
Preferences terminal theme

### ISSUE THREAD

**Issue by Maartz** [AuroraEditor/AuroraEditor#350] opened 2022-12-29 08:42 UTC
### Description

Whenever you want to change the theme of the terminal, you can't extend the window the proceed further.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/13407086/209925696-74b0e29f-96f1-4ad2-b3b2-6c22b42da787.png">

That's probably due to the constraints added to the view.

### To Reproduce

1. Open up AE
2. Cmd + , or AuroraEditor > Settings
3. Click "Themes"
4. Click "Terminal"

### Expected behavior

The expected behavior is that the window expands to let the user interacts with the content of the view.

### Version information

Aurora Editor: 1.0
Commit: 564e8931
MacOS: Ventura 13.2
Xcode: 14.2

**Comment by 0xWDG** [comment] 2022-12-29 10:18
Seems related to https://github.com/AuroraEditor/AuroraEditor/issues/291

**Comment by Maartz** [comment] 2022-12-29 10:23
Right, didn't checked in the closed ones.

**Comment by 0xWDG** [comment] 2022-12-29 10:25
No problem, i was not able to reproduce it so i expected that it was fixed. seems it's still an issue.

**Comment by Maartz** [comment] 2022-12-29 15:53
So I've checked this and it seems that it doesn't come from the `ThemePreferencesView`.
AFAI understand, it's linked to the `PreferencesView`, especially the `settingContentView`.
It can't expand its parent frame. So I'd naively tinker with it until find the good balance between readbility and effectiveness.

**Comment by 0xWDG** [comment] 2024-11-03 12:15
Whoops, this has been fixed in https://github.com/AuroraEditor/AuroraEditor/pull/420

**Closed by 0xWDG** 2024-11-03 12:15 UTC
Labels: bug, Verified, hacktoberfest
