### ISSUE TITLE
Preferences screen shifted

### ISSUE THREAD

**Issue by Angelk90** [AuroraEditor/AuroraEditor#291] opened 2022-10-11 21:39 UTC
### Description

<img width="779" alt="Schermata 2022-10-11 alle 23 37 48" src="https://user-images.githubusercontent.com/20476002/195203183-7cc95664-0563-40c7-9e62-8c0470da3dac.png">

### To Reproduce

1) Open settings
2) Themes
3) Terminal

### Version information

Aurora Editor: 1.0 (1)
Commit: f18b3cd1f118d1986d228f0f41077864165c66d3
MacOS: 12.5.1 (21G83)
Xcode: 14.0.1 (14A400)

**Comment by KaiTheRedNinja** [comment] 2022-10-11 22:58
This is an issue with the swiftui navigation view. After the editor is settled I’ll migrate it to a NSSplitView to fix this and related problems.

**Comment by 0xWDG** [comment] 2022-12-27 19:42
I'm not able to reproduce, closing this for now.

**Closed by 0xWDG** 2022-12-27 19:42 UTC
Labels: bug, UI, Verified
